{"name":"getNumberTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nMethod ExpectedExceptionConcept.getNumberTest()[pri:0, instance:TestngSessions.ExpectedExceptionConcept@63718b93] should have thrown an exception of any of types [class java.lang.ArithmeticException, class java.lang.NullPointerException]","trace":"org.testng.TestException: \nMethod ExpectedExceptionConcept.getNumberTest()[pri:0, instance:TestngSessions.ExpectedExceptionConcept@63718b93] should have thrown an exception of any of types [class java.lang.ArithmeticException, class java.lang.NullPointerException]\r\n\tat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)\r\n\tat org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:615)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1610406529197,"stop":1610406529215,"uuid":"7fd1bc6f-0faf-4b67-b489-3efdc1b57b89","historyId":"f8d9b924034897462635c46bb52b4102","fullName":"TestngSessions.ExpectedExceptionConcept.getNumberTest","labels":[{"name":"package","value":"TestngSessions.ExpectedExceptionConcept"},{"name":"testClass","value":"TestngSessions.ExpectedExceptionConcept"},{"name":"testMethod","value":"getNumberTest"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"TestngSessions.ExpectedExceptionConcept"},{"name":"host","value":"DESKTOP-ERMO56R"},{"name":"thread","value":"20992@DESKTOP-ERMO56R.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}